name: Sync Cardinal-Cryptography repo with Set-Zero-Foundation repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-24.04
    if: ${{ github.repository == 'Cardinal-Cryptography/SetBFT'}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "main"
          token: ${{ secrets.SYNCAZF }}
      - name: Push to Set-Zero-Foundation
        run: git push https://x-access-token:${{ secrets.SYNCAZF }}@github.com/set-zero-foundation/SetBFT.git
