name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-rust:
    name: Rust Check & Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install mise
        uses: jdx/mise-action@v2

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Cargo Check
        run: mise run check

      - name: Cargo Clippy
        run: mise run clippy

  test-rust:
    name: Rust Tests
    runs-on: ubuntu-latest
    needs: check-rust
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install mise
        uses: jdx/mise-action@v2

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run Tests
        run: mise run test:rust

  test-js:
    name: JS Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2

      - name: Install dependencies
        run: mise run init

      - name: Run Tests
        run: mise run test:js
