name: Command PrDoc

on:
  workflow_dispatch:
    inputs:
      pr:
        type: number
        description: Number of the Pull Request
        required: true

concurrency:
  group: command-prdoc
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  cmd-prdoc:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Install gh cli
        id: gh
        uses: ./.github/actions/set-up-gh
        with:
          pr-number: ${{ inputs.pr }}
          GH_TOKEN: ${{ github.token }}

      - name: Install changelogger
        run: cargo install changelogger-cli

      - name: Generate PrDoc
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          changelogger prdoc generate --pr "${{ inputs.pr }}" --force

      - name: Report failure
        if: ${{ failure() }}
        run: gh pr comment ${{ inputs.pr }} --body "Command failed ❌"
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add prdoc for PR #${{ inputs.pr }}"
          file_pattern: "prdoc/*.prdoc"
