---
name: GH Action YAML linter

on:
  merge_group:
  pull_request:
    paths:
      - '.github/**.yml'
      - '.github/**.yaml'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  main:
    name: YAML Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: LINT | Execute YAML linter
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq yamllint
          yamllint .github/workflows/ -c .yamllint
